import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { auth } from "firebase";
import { useAuth } from "../lib/auth";

export default function Home() {
  const auth = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>F-Feedback</h1>

        <button onClick={(e) => auth.singinWithGithub()}>Sign In With GitHub</button>
        <button onClick={(e) => auth.signinWithGoogle()}>Sign In With Google</button>
        {auth?.user && <button onClick={(e) => auth.signout()}>Sign Out</button>}

        <div>{auth?.user?.email}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        ></a>
      </footer>
    </div>
  );
}
